### ISSUE TITLE
Some questions about the rivens mod.

### ISSUE THREAD

**Issue by handouy** [leonardodalinky/pywmapi#10]
May I ask whether this project does not support the acquisition of users' rivens mod data?

**Comment by leonardodalinky** [comment]
**No**, at least for now. It would be planned in the near future when I'm available. 

Also, any PR is welcome if anyone make contributions :)

**Comment by handouy** [comment]
> **No**, at least for now. It would be planned in the near future when I'm available.
> 
> Also, any PR is welcome if anyone make contributions :)
好的,感谢大佬开发了这么方便的项目~(看了一下原来大佬也是国人
我根据你的获取订单的部分 自己修改了一个拿紫卡资料的 方法 (萌新 比较草率 就不提交更新了
